# Generated by Django 5.2.17 on 2026-08-17 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[("TEAM", "팀 평가"), ("PEER", "개인 평가")], max_length=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "copied_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copies",
                        to="rounds.questiontemplate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("category", "name"),
            },
        ),
        migrations.CreateModel(
            name="EvaluationRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "준비 중"),
                            ("IN_PROGRESS", "평가 진행 중"),
                            ("COMPLETED", "완료"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("evaluation_start_at", models.DateTimeField()),
                ("evaluation_end_at", models.DateTimeField()),
                ("target_team_count", models.PositiveSmallIntegerField(default=2)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "peer_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="peer_rounds",
                        to="rounds.questiontemplate",
                    ),
                ),
                (
                    "team_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_rounds",
                        to="rounds.questiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RoundParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("student_number_snapshot", models.CharField(max_length=32)),
                ("display_name_snapshot", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="rounds.evaluationround",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="round_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("student_number_snapshot", "id"),
            },
        ),
        migrations.CreateModel(
            name="TemplateQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[("RATING_5", "1~5점"), ("TEXT", "자유 서술")], max_length=12
                    ),
                ),
                ("prompt", models.CharField(max_length=500)),
                ("is_required", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="rounds.questiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="questiontemplate",
            index=models.Index(fields=["category", "name"], name="rounds_ques_categor_7577e9_idx"),
        ),
        migrations.AddConstraint(
            model_name="questiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="rounds_template_name_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("copied_from__isnull", True),
                    models.Q(("copied_from", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="rounds_template_not_self_copy",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationround",
            constraint=models.CheckConstraint(
                condition=models.Q(("evaluation_start_at__lt", models.F("evaluation_end_at"))),
                name="rounds_evaluation_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationround",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_team_count__gte", 2)),
                name="rounds_target_team_count_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("status",),
                name="rounds_single_in_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="roundparticipant",
            constraint=models.UniqueConstraint(
                fields=("round", "user"), name="rounds_participant_user_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="roundparticipant",
            constraint=models.UniqueConstraint(
                fields=("round", "student_number_snapshot"), name="rounds_participant_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatequestion",
            constraint=models.UniqueConstraint(
                fields=("template", "display_order"), name="rounds_question_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatequestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 1)), name="rounds_question_order_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatequestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("prompt", ""), _negated=True),
                name="rounds_question_prompt_not_blank",
            ),
        ),
    ]
