# Generated by Django 5.2.17 on 2026-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationround',
            name='auto_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
