# Generated by Django 5.2.17 on 2026-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개 여부')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
