# Generated by Django 5.2.17 on 2026-08-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rounds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatequestion",
            name="competency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEAMWORK", "팀워크"),
                    ("PROBLEM_SOLVING", "문제해결"),
                    ("DEV_UNDERSTANDING", "개발이해도"),
                    ("RESPONSIBILITY", "책임감"),
                    ("COMMUNICATION", "커뮤니케이션"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
