# Generated by Django 5.2.17 on 2026-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rounds", "0005_questiontemplate_archived_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluationround",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "평가 회차",
                "verbose_name_plural": "평가 회차 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="questiontemplate",
            options={
                "ordering": ("category", "name"),
                "verbose_name": "문항 템플릿",
                "verbose_name_plural": "문항 템플릿 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="roundparticipant",
            options={
                "ordering": ("student_number_snapshot", "id"),
                "verbose_name": "회차 참가자",
                "verbose_name_plural": "회차 참가자 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="templatequestion",
            options={
                "ordering": ("display_order", "id"),
                "verbose_name": "문항",
                "verbose_name_plural": "문항 목록",
            },
        ),
    ]
