# Generated by Django 5.2.17 on 2026-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ("team_number",),
                "verbose_name": "팀",
                "verbose_name_plural": "팀 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="teammembership",
            options={
                "ordering": ("team__team_number", "participant__student_number_snapshot"),
                "verbose_name": "팀 구성원",
                "verbose_name_plural": "팀 구성원 목록",
            },
        ),
    ]
