# Generated by Django 5.2.17 on 2026-08-15 07:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="사전 등록 이메일"),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                (
                    "session_info",
                    models.CharField(default="4기", max_length=50, verbose_name="기수/세션"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "학생"), ("TUTOR", "튜터"), ("ADMIN", "관리자")],
                        default="STUDENT",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="등록일")),
            ],
            options={
                "verbose_name": "화이트리스트",
                "verbose_name_plural": "화이트리스트 목록",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "학생"), ("TUTOR", "튜터"), ("ADMIN", "관리자")],
                        default="STUDENT",
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "승인 대기"),
                            ("APPROVED", "승인 완료"),
                            ("REJECTED", "승인 거절"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="승인 상태",
                    ),
                ),
                (
                    "is_onboarded",
                    models.BooleanField(default=False, verbose_name="온보딩 완료 여부"),
                ),
                (
                    "session_info",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="기수/세션"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="전화번호"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/", verbose_name="프로필 사진"
                    ),
                ),
                (
                    "is_social_account",
                    models.BooleanField(default=False, verbose_name="소셜 로그인 계정 여부"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
