# Generated by Django 5.2.17 on 2026-08-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_whitelistemail_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="연락처"),
        ),
        migrations.AlterField(
            model_name="user",
            name="session_info",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="기수 정보",
            ),
        ),
        migrations.AlterField(
            model_name="whitelistemail",
            name="session_info",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="배정 기수",
            ),
        ),
    ]
