# Generated by Django 5.2.17 on 2026-08-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_auththrottlebucket_emailresendcooldown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name="수강생 식별번호"
            ),
        ),
    ]
