# Generated by Django 5.2.17 on 2026-08-17 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_student_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailResendCooldown",
        ),
    ]
