# Generated by Django 5.2.17 on 2026-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_emailresendcooldown"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/", verbose_name="프로필 사진"
            ),
        ),
    ]
