# Generated by Django 5.2.17 on 2026-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_emailresendcooldown"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("code", models.CharField(max_length=6, verbose_name="인증코드 6자리")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("SIGNUP", "회원가입"), ("PASSWORD_RESET", "비밀번호 재설정")],
                        max_length=20,
                        verbose_name="인증 목적",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="인증 완료 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="만료 일시")),
            ],
            options={
                "verbose_name": "이메일 인증코드",
                "verbose_name_plural": "이메일 인증코드 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
