# Generated by Django 5.2.17 on 2026-08-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_staff_follows_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="muted_email_categories",
            field=models.JSONField(blank=True, default=list, verbose_name="메일로 받지 않을 알림"),
        ),
    ]
