# Generated by Django 5.2.17 on 2026-08-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0003_aiprompt_aiusagelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatHistory",
            fields=[
                ("chat_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("chat_data", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "prd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_histories",
                        to="ideas.prdproject",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_histories",
                        to="ideas.prdsection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "AI_Chat_Histories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prd", "section", "user"), name="ideas_chat_history_unique"
                    )
                ],
            },
        ),
    ]
