# Generated by Django 5.2.17 on 2026-09-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0004_aichathistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprompt",
            name="feature_type",
            field=models.CharField(
                choices=[("CHAT", "채팅"), ("COACHING", "코칭"), ("GENERATE", "생성")],
                max_length=20,
            ),
        ),
    ]
