# Generated by Django 5.2.17 on 2026-09-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0005_alter_aiprompt_feature_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="postit",
            name="column_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postits",
                to="ideas.prdsection",
            ),
        ),
    ]
