# Generated by Django 5.2.17 on 2026-08-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rounds", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("TEAM", "팀 평가"), ("PEER", "개인 평가")], max_length=8
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="written_reviews",
                        to="rounds.roundparticipant",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_submissions",
                        to="rounds.evaluationround",
                    ),
                ),
                (
                    "target_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_peer_reviews",
                        to="rounds.roundparticipant",
                    ),
                ),
                (
                    "target_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_reviews",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ("submitted_at",),
            },
        ),
        migrations.CreateModel(
            name="ReviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating_value", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="rounds.templatequestion",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="reviews.reviewsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("question__display_order",),
            },
        ),
        migrations.AddConstraint(
            model_name="reviewsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("review_type", "TEAM"),
                        ("target_participant__isnull", True),
                        ("target_team__isnull", False),
                    ),
                    models.Q(
                        ("review_type", "PEER"),
                        ("target_participant__isnull", False),
                        ("target_team__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="reviews_submission_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_participant__isnull", True),
                    models.Q(("evaluator", models.F("target_participant")), _negated=True),
                    _connector="OR",
                ),
                name="reviews_no_self_peer_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_type", "TEAM")),
                fields=("round", "evaluator", "target_team"),
                name="reviews_team_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_type", "PEER")),
                fields=("round", "evaluator", "target_participant"),
                name="reviews_peer_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="reviews_answer_question_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rating_value__isnull", False), ("text_value", "")),
                    models.Q(
                        ("rating_value__isnull", True), models.Q(("text_value", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="reviews_answer_exactly_one_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating_value__isnull", True),
                    models.Q(("rating_value__gte", 1), ("rating_value__lte", 5)),
                    _connector="OR",
                ),
                name="reviews_answer_rating_range",
            ),
        ),
    ]
