# Generated by Django 5.2.17 on 2026-08-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
        ("rounds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewFinalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("TEAM", "팀 평가"), ("PEER", "개인 평가")], max_length=8
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_final_submissions",
                        to="rounds.roundparticipant",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_final_submissions",
                        to="rounds.evaluationround",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "evaluator", "review_type"),
                        name="reviews_final_submission_unique",
                    )
                ],
            },
        ),
    ]
