# Generated by Django 5.2.17 on 2026-08-19 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_tutorreview_tutorreviewanswer_and_more"),
        ("rounds", "0004_evaluationround_personal_score_weight_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorTeamReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutor_team_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutor_team_reviews",
                        to="rounds.evaluationround",
                    ),
                ),
                (
                    "target_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_tutor_reviews",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ("target_team__team_number", "id"),
            },
        ),
        migrations.CreateModel(
            name="TutorTeamReviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating_value", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tutor_team_answers",
                        to="rounds.templatequestion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="reviews.tutorteamreview",
                    ),
                ),
            ],
            options={
                "ordering": ("question__display_order",),
            },
        ),
        migrations.AddConstraint(
            model_name="tutorteamreview",
            constraint=models.UniqueConstraint(
                fields=("round", "evaluator", "target_team"),
                name="reviews_tutor_team_review_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorteamreviewanswer",
            constraint=models.UniqueConstraint(
                fields=("review", "question"), name="reviews_tutor_team_answer_question_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorteamreviewanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rating_value__isnull", False), ("text_value", "")),
                    models.Q(
                        ("rating_value__isnull", True), models.Q(("text_value", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="reviews_tutor_team_answer_exactly_one_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="tutorteamreviewanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating_value__isnull", True),
                    models.Q(("rating_value__gte", 1), ("rating_value__lte", 5)),
                    _connector="OR",
                ),
                name="reviews_tutor_team_answer_rating_range",
            ),
        ),
    ]
