# Generated by Django 5.2.17 on 2026-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_tutorteamreview_tutorteamreviewanswer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewsubmission",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="건별 확정 시각. 유형 전체를 잠그는 ReviewFinalSubmission과 달리, 이 건 하나만 더 이상 고칠 수 없게 한다(현재는 개인 평가에서만 쓴다).",
                null=True,
            ),
        ),
    ]
