# Generated by Django 5.2.17 on 2026-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_reviewsubmission_locked_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviewanswer",
            options={
                "ordering": ("question__display_order",),
                "verbose_name": "평가 응답",
                "verbose_name_plural": "평가 응답 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="reviewfinalsubmission",
            options={"verbose_name": "최종 제출", "verbose_name_plural": "최종 제출 목록"},
        ),
        migrations.AlterModelOptions(
            name="reviewsubmission",
            options={
                "ordering": ("submitted_at",),
                "verbose_name": "평가 제출",
                "verbose_name_plural": "평가 제출 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="tutorreview",
            options={
                "ordering": ("target_participant__student_number_snapshot", "id"),
                "verbose_name": "튜터 개인평가",
                "verbose_name_plural": "튜터 개인평가 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="tutorreviewanswer",
            options={
                "ordering": ("question__display_order",),
                "verbose_name": "튜터 개인평가 응답",
                "verbose_name_plural": "튜터 개인평가 응답 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="tutorteamreview",
            options={
                "ordering": ("target_team__team_number", "id"),
                "verbose_name": "튜터 팀평가",
                "verbose_name_plural": "튜터 팀평가 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="tutorteamreviewanswer",
            options={
                "ordering": ("question__display_order",),
                "verbose_name": "튜터 팀평가 응답",
                "verbose_name_plural": "튜터 팀평가 응답 목록",
            },
        ),
    ]
