# Generated by Django 5.2.17 on 2026-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "감사 기록",
                "verbose_name_plural": "감사 기록 목록",
            },
        ),
    ]
