# Generated by Django 5.2.17 on 2026-08-19 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NOTICE", "공지"),
                            ("ROUND_CREATED", "새 회차"),
                            ("TEAM_CREATED", "새 팀"),
                            ("ROUND_COMPLETED", "평가 종료"),
                        ],
                        max_length=20,
                        verbose_name="종류",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("message", models.CharField(blank=True, max_length=300, verbose_name="내용")),
                ("link", models.CharField(blank=True, max_length=300, verbose_name="이동 경로")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="읽은 시각")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수신자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"], name="notificatio_recipie_564b1f_idx"
                    )
                ],
            },
        ),
    ]
