# Generated by Django 5.2.17 on 2026-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("NOTICE", "공지"),
                    ("ROUND_CREATED", "새 회차"),
                    ("TEAM_CREATED", "새 팀"),
                    ("ROUND_COMPLETED", "평가 종료"),
                    ("SUBMISSION_REMINDER", "제출 안내"),
                    ("PARTICIPANT_COMPLETED", "제출 완료"),
                ],
                max_length=30,
                verbose_name="종류",
            ),
        ),
    ]
